version: "3"

services:
  nginx:
    container_name: bas_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./server:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - php
    tty: true
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: bas_php
    volumes:
      - ./server:/usr/share/nginx/html
    tty: true
  mysql:
    container_name: bas_mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bas
      MYSQL_USER: bas
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql/tmp:/tmp
      - ./docker/mysql/mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d/:/docker-entrypoint-initdb.d
    tty: true
  minio:
    container_name: bas_minio
    image: "minio/minio"
    environment:
      # MINIO_ACCESS_KEY
      MINIO_ROOT_USER: bas
      # MINIO_SECRET_KEY
      MINIO_ROOT_PASSWORD: password
    entrypoint: bash
    # `--address :9999` で、MinIO の API のポートを指定しています
    # `--console-address :9001` でコンソールの ポートを指定しています。
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
    volumes:
      - ./docker/minio/data:/export
    ports:
      - "9000:9000"
      - "9001:9001"
    tty: true
  mailhog:
    container_name: bas_mailhog
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "8025:8025"
    tty:
      true